//define shared library
@Library('Jenkins-shared@feature/tf') _

//start of npipeline
pipeline{
      agent any

      environment {
        GOOGLE_APPLICATION_CREDENTIALS = ''
      }

      stages{
        stage('Configure'){
          steps{
            withCredentials([file(credentialsId: 'SA_AUTH', passVariable: 'SERVICE_ACCOUNT_KEY')]) {
              
              sh "gcloud config set project learn-dev-436914  
            
            }
          }
        }

        stage('Init') {
          steps {
            script {
              terraform.init(terraformDir: 'GCP/compute_instance')
            }
          }
        }

        stage('Plan') {
            steps {
              withCredentials([file(credentialsId: 'SA_AUTH', passVariable: 'SERVICE_ACCOUNT_KEY')]) {

                script {
                    terraform.plan(terraformDir: 'GCP/compute_instance')
                }
              }
            }
        }



    }
}