//define shared library
@Library('Jenkins-shared@feature/tf') _

//start of npipeline
pipeline{
      agent any

      environment {
        GOOGLE_APPLICATION_CREDENTIALS = ''
      }

      stages{
        stage('Configure'){
          steps{
            withCredentials([file(credentialsId: 'SA_AUTH',variable: 'SERVICE_ACCOUNT_KEY')]) {
              
              sh 'env.GOOGLE_APPLICATION_CREDENTIALS=${SERVICE_ACCOUNT_KEY}'
              println("${SERVICE_ACCOUNT_KEY}")
              println("The google authenicate" + ${env.GOOGLE_APPLICATION_CREDENTIALS} )
            
            }
          }
        }

        stage('Init') {
          steps {
            script {
              terraform.init(terraformDir: 'GCP/compute_instance')
            }
          }
        }

        stage('Plan') {
            steps {
                script {
                    terraform.plan(terraformDir: 'GCP/compute_instance')
                }
            }
        }



    }
}